#!/usr/bin/env zsh

wenv_def() {
    WENV_DIR=""
    WENV_DEPS=()
    WENV_PROJECT=''
    WENV_TASK=''
    WENV_EXTENSIONS=('c' 'edit')

    startup_wenv() {}
    shutdown_wenv() {}
    bootstrap_wenv() {}
}

declare -Ag wenv_dirs=()
declare -Ag wenv_files=()
