#!/bin/zsh

wenv_setup() {
    WENV_DIR=""
    WENV_DEPS=()
    WENV_PROJECT=''
    WENV_BRANCH='master'
    WENV_TASK=''
    WENV_GITDIR=""

    wenv_bootstrap() {}
    wenv_init() {}
    wenv_shutdown() {}
}
