#!/usr/bin/env zsh

export WENV_HISTDIR="${XDG_CACHE_HOME:-$HOME/.cache}/wenv/history"
export WENV_HISTFILE=$WENV_HISTDIR/$(sed 's/\//-/g' <<< $WENV)

# ensure history file (+ directory) exists
if [[ ! -f $WENV_HISTFILE ]]; then
    mkdir -p $WENV_HISTDIR
    touch $WENV_HISTFILE
fi

# hook to update the wenv-specific history file every time the general history is updated
_update_wenv_history() {
    print -sr -- ${1%%$'\n'}
    fc -pa $WENV_HISTFILE
}
# add-zsh-hook zshaddhistory _update_wenv_history

# zsh widget to search the wenv-specific history
_search_wenv_history() {
    fc -pa $WENV_HISTFILE
    # fc -R
    bindkey "^T" history-incremental-search-backward
    zle history-incremental-search-backward
    bindkey "^T" _search_wenv_history
    # fc -P
}
zle -N _search_wenv_history
bindkey "^T" _search_wenv_history
