#!/bin/zsh

export SSH_AUTH_SOCK="${XDG_RUNTIME_DIR}/ssh-agent.socket"

ssh_agent() {
    case "$1" in
        'start')
            systemctl --user start ssh-agent
            ;;
        'stop')
            systemctl --user stop ssh-agent
            ;;
        'status')
            systemctl --user status ssh-agent
            ;;
        *)
            echo "invalid argument: $1" >2
            ;;
    esac
}
