#!/usr/bin/zsh

wenv_tmux_layout() {
    local layout="$1"
    shift
    case "$layout" in
        dev)
            wenv_tmux_split v
            tmux resize-pane -y 7
            [[ -n "$@" ]] && tmux send-keys "$*" 'Enter'
            tmux select-pane -U
            ;;
        devloop)
            local watch='git'
            [[ "$1" == '-w' ]] && watch="$2" && shift 2
            wenv_tmux_layout 'dev' "monitor $watch $*"
            ;;
        dev-tasks)
            local watch='git'
            [[ "$1" == '-w' ]] && watch="$2" && shift 2
            wenv_tmux_split v
            tmux resize-pane -y 7
            [[ -n "$@" ]] && tmux send-keys "monitor $watch $@" 'Enter'
            wenv_tmux_split h
            tmux send-keys 'wenv task show' 'Enter'
            tmux select-pane -L
            tmux select-pane -U
            ;;
        tasks)
            wenv_tmux_split v
            tmux resize-pane -y 7
            tmux send-keys 'wenv task show' 'Enter'
            tmux select-pane -U
            ;;
        split-tasks)
            wenv_tmux_layout tasks
            wenv_tmux_split h
            [[ -n "$@" ]] && tmux send-keys "$@" 'Enter'
            tmux select-pane -L
            ;;
        *)
            return 1
            ;;
    esac
}
